config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  resources :cocktails do
    resources :doses, only: [ :create, :new, :destroy ]
  end
  resources :doses, only: [:destroy]
  root "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :ingredients, through: :doses, dependent: :destroy
  has_many :doses
  has_attachment :photo

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
      params.require(:cocktail).permit(:name, :photo)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:create]

  def create
    @new_dose = Dose.new(dose_params)
    @new_dose.cocktail = @cocktail
    @ingredients = Ingredient.all
    if @new_dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'background' %>)">
  <div class="banner-content">
    <h1>Welcome to Cocktails</h1>
    <p>Your best coktails</p>
     <%= link_to new_cocktail_path, {class: "btn btn-primary"} do  %>
  <% 'Create a cocktail' %>
  <% end %>
  </div>
</div>

<div class="wrapper">
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
            url('<%= cl_image_path cocktail.photo.path, height: 300, width: 400, crop: :fill %>')">
            <div class="card-description">
              <h2><%= cocktail.name %></h2>
            </div>
            <%= link_to '', cocktail, {:class => "card-link"} %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>New cocktail</h1>

<%= render 'form' %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1>Show cocktail</h1>

<p><%= @cocktail.name %></p>

<p>
<% @cocktail.doses.each do |dose| %>
  <p>Dose : <%= dose.description %> </p>
  <P>Ingredient : <%= dose.ingredient.name %></p>
  <p><%= link_to 'Delete', dose_path(dose), method: :delete %></p>
<% end %>
</p>

<% if @cocktail.photo? %>
  <%= cl_image_tag @cocktail.photo.path, width: 200, height: 300, crop: :fill %>
<% end %>

<h3>Add ingredient</h3>

<%= render 'doses/form',
  cocktail: @cocktail,
  dose: @cocktail.doses.new %>

<%= link_to 'Edit', edit_cocktail_path(@cocktail) %>
<%= link_to 'Destroy', cocktail_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%= link_to 'Back', cocktails_path %>

app/views/doses/_form.html.erb
<%= simple_form_for [ cocktail, dose ] do |f| %>
  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.select :ingredient_id, options_from_collection_for_select(Ingredient.all, 'id', 'name') %>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <%= yield %>

    <div class="share-links">
      <a href="#" class="share-link bg-facebook">
        <i class="fa fa-facebook"></i>
      </a>
      <a href="#" class="share-link bg-twitter">
        <i class="fa fa-twitter"></i>
      </a>
      <a href="#" class="share-link bg-email">
        <i class="fa fa-envelope-o"></i>
      </a>
      <a href="#" class="share-link bg-text">
        <i class="fa fa-mobile"></i>
      </a>
    </div>
  </body>
</html>